spring:
  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  session:
    store-type: redis

  redis:
    host: ${redis-server:localhost}
    port: 6379


  cloud:
    stream:
      bindings:
        deliveryCommandOutput:
          destination: DeliveryCommand
        createOrderSagaReplyInput:
          destination: CreateOrderSagaReply

  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest

service:
  dns:
    goods: http://localhost:8082
    account: http://localhost:8083


